// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package hotel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HotelClient is the client API for Hotel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HotelClient interface {
	CreateHotel(ctx context.Context, in *HotelCreate, opts ...grpc.CallOption) (*HotelResponse, error)
}

type hotelClient struct {
	cc grpc.ClientConnInterface
}

func NewHotelClient(cc grpc.ClientConnInterface) HotelClient {
	return &hotelClient{cc}
}

func (c *hotelClient) CreateHotel(ctx context.Context, in *HotelCreate, opts ...grpc.CallOption) (*HotelResponse, error) {
	out := new(HotelResponse)
	err := c.cc.Invoke(ctx, "/Hotel/CreateHotel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotelServer is the server API for Hotel service.
// All implementations must embed UnimplementedHotelServer
// for forward compatibility
type HotelServer interface {
	CreateHotel(context.Context, *HotelCreate) (*HotelResponse, error)
	mustEmbedUnimplementedHotelServer()
}

// UnimplementedHotelServer must be embedded to have forward compatible implementations.
type UnimplementedHotelServer struct {
}

func (UnimplementedHotelServer) CreateHotel(context.Context, *HotelCreate) (*HotelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHotel not implemented")
}
func (UnimplementedHotelServer) mustEmbedUnimplementedHotelServer() {}

// UnsafeHotelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HotelServer will
// result in compilation errors.
type UnsafeHotelServer interface {
	mustEmbedUnimplementedHotelServer()
}

func RegisterHotelServer(s grpc.ServiceRegistrar, srv HotelServer) {
	s.RegisterService(&Hotel_ServiceDesc, srv)
}

func _Hotel_CreateHotel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotelCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServer).CreateHotel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hotel/CreateHotel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServer).CreateHotel(ctx, req.(*HotelCreate))
	}
	return interceptor(ctx, in, info, handler)
}

// Hotel_ServiceDesc is the grpc.ServiceDesc for Hotel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hotel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Hotel",
	HandlerType: (*HotelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHotel",
			Handler:    _Hotel_CreateHotel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hotel/hotel.proto",
}
